export const TYPE = {
  TASK_ADD: "TASK_ADD",
  TASK_TOGGLE_CHECKED: "TASK_TOGGLE_CHECKED",
  TASK_DELETE: "TASK_DELETE",
  TASK_CLEAR: "TASK_CLEAR",
  TASK_TOGGLE_CHECKED_ALL: "TASK_TOGGLE_CHECKED_ALL",
};
